AllCops:
  Exclude:
    - "spec/**/*"

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Style/Lambda:
  EnforcedStyle: literal

Style/LineEndConcatenation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/Next:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/ModuleLength:
  Max: 500

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/IndentationStyle:
  IndentationWidth: 2

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true
